using System;
using System.Collections.Generic;
using NUnit.Framework;

namespace Starhermit.Tests
{
    /// <summary>
    /// The release gate: every operation the deployed API exposes is either mapped to a typed SDK
    /// method or explicitly classified with a reason. A new endpoint on the server therefore shows up
    /// here as a failing test, not as a gap somebody notices months later.
    /// </summary>
    /// <remarks>
    /// The data these tests read is generated by <c>tools/generate_coverage.py</c> straight from the
    /// backend's controllers, so it cannot drift from the contract by being edited.
    /// </remarks>
    [TestFixture]
    public class ContractCoverageTests
    {
        [Test]
        public void EveryApiOperation_IsMappedOrClassified()
        {
            if (ApiCoverage.Unmapped.Length == 0) Assert.Pass();

            var report = new System.Text.StringBuilder("The API exposes operations this SDK neither maps nor classifies:\n");
            foreach (var operation in ApiCoverage.Unmapped)
                report.Append($"  {operation.Method} {operation.Path}  ({operation.ApiOperation})\n");
            report.Append("Map them, or classify them with a reason in tools/generate_coverage.py.");
            Assert.Fail(report.ToString());
        }

        [Test]
        public void MappedOperations_NameAnSdkOperation()
        {
            foreach (var operation in ApiCoverage.Mapped)
            {
                Assert.IsFalse(
                    string.IsNullOrWhiteSpace(operation.SdkOperation),
                    $"{operation.Method} {operation.Path} claims to be mapped but names no SDK operation");
                StringAssert.Contains(".", operation.SdkOperation!, "operation ids read as <area>.<operation>");
            }
        }

        [Test]
        public void ClassifiedOperations_ExplainThemselves()
        {
            foreach (var operation in ApiCoverage.Classified)
            {
                Assert.IsFalse(
                    string.IsNullOrWhiteSpace(operation.Classification),
                    $"{operation.Method} {operation.Path} is untyped without a stated reason");
                Assert.Greater(operation.Classification!.Length, 30, "a reason has to actually say something");
            }
        }

        [Test]
        public void TheWholeApiSurfaceIsAccountedFor()
        {
            var total = ApiCoverage.Mapped.Length + ApiCoverage.Classified.Length + ApiCoverage.Unmapped.Length;

            Assert.Greater(total, 150, "the manifest should describe the whole v1 surface");
            Assert.AreEqual(0, ApiCoverage.Unmapped.Length);
        }

        [Test]
        public void EverySocketProtocol_HasAConnectionType()
        {
            var assembly = typeof(StarhermitClient).Assembly;

            foreach (var (protocol, path, connection) in ApiCoverage.Sockets)
            {
                var type = assembly.GetType("Starhermit." + connection);
                Assert.IsNotNull(type, $"the {protocol} protocol names {connection}, which does not exist");
                Assert.IsTrue(
                    typeof(StarhermitConnection).IsAssignableFrom(type!),
                    $"{connection} must be a Starhermit connection so it inherits the shared socket rules");
                StringAssert.StartsWith("/ws/v1/", path);
            }
        }

        [Test]
        public void SdkOperationIds_AreUnique()
        {
            var seen = new Dictionary<string, string>(StringComparer.Ordinal);

            foreach (var operation in ApiCoverage.Mapped)
            {
                var id = operation.SdkOperation!;
                if (seen.TryGetValue(id, out var first))
                {
                    Assert.Fail($"'{id}' is claimed by both {first} and {operation.Method} {operation.Path}; " +
                                "telemetry and logs identify operations by this id, so it has to be unique");
                }

                seen[id] = $"{operation.Method} {operation.Path}";
            }
        }
    }
}
